# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-slickmap}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Reynolds"]
  s.date = %q{2010-05-22}
  s.email = %q{tdreyno@gmail.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "compass-slickmap.gemspec",
     "lib/slickmap.rb",
     "lib/stylesheets/_slickmap.scss",
     "lib/templates/project/L1-center.png",
     "lib/templates/project/L1-left.png",
     "lib/templates/project/L1-right.png",
     "lib/templates/project/L3-bottom.png",
     "lib/templates/project/L3-center.png",
     "lib/templates/project/L3-li-top.png",
     "lib/templates/project/L3-ul-top.png",
     "lib/templates/project/manifest.rb",
     "lib/templates/project/sitemap.scss",
     "lib/templates/project/vertical-line.png",
     "lib/templates/project/white-highlight.png"
  ]
  s.homepage = %q{http://github.com/tdreyno/compass-slickmap}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An implementation of SlickmapCSS sitemap in SCSS/Sass3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 3.0"])
      s.add_runtime_dependency(%q<compass>, [">= 0.10"])
    else
      s.add_dependency(%q<haml>, [">= 3.0"])
      s.add_dependency(%q<compass>, [">= 0.10"])
    end
  else
    s.add_dependency(%q<haml>, [">= 3.0"])
    s.add_dependency(%q<compass>, [">= 0.10"])
  end
end
